"""add provicia_distrito_canton_models

Revision ID: 18e8f88c3f29
Revises: 209d7cc80666
Create Date: 2025-03-02 00:44:46.706103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '18e8f88c3f29'
down_revision: Union[str, None] = '209d7cc80666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_index(op.f('ix_categorias_name'), 'categorias', ['name'], unique=False)
    op.create_table('provincias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provincias_id'), 'provincias', ['id'], unique=False)
    op.create_index(op.f('ix_provincias_name'), 'provincias', ['name'], unique=False)
    op.create_table('cantones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cantones_id'), 'cantones', ['id'], unique=False)
    op.create_index(op.f('ix_cantones_name'), 'cantones', ['name'], unique=False)
    op.create_table('distritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('canton_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['canton_id'], ['cantones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distritos_id'), 'distritos', ['id'], unique=False)
    op.create_index(op.f('ix_distritos_name'), 'distritos', ['name'], unique=False)
    op.drop_index('ix_categories_id', table_name='categories')
    op.drop_index('ix_categories_name', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.create_index('ix_categories_id', 'categories', ['id'], unique=False)
    op.drop_index(op.f('ix_distritos_name'), table_name='distritos')
    op.drop_index(op.f('ix_distritos_id'), table_name='distritos')
    op.drop_table('distritos')
    op.drop_index(op.f('ix_cantones_name'), table_name='cantones')
    op.drop_index(op.f('ix_cantones_id'), table_name='cantones')
    op.drop_table('cantones')
    op.drop_index(op.f('ix_provincias_name'), table_name='provincias')
    op.drop_index(op.f('ix_provincias_id'), table_name='provincias')
    op.drop_table('provincias')
    op.drop_index(op.f('ix_categorias_name'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
