"""add_image_field_on_legend

Revision ID: 2ea20e238fdd
Revises: fdf3c0c9c468
Create Date: 2025-03-03 01:16:13.822046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea20e238fdd'
down_revision: Union[str, None] = 'fdf3c0c9c468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leyendas', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leyendas', 'image')
    # ### end Alembic commands ###
