"""add legend_model

Revision ID: fdf3c0c9c468
Revises: 18e8f88c3f29
Create Date: 2025-03-02 01:17:11.290314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf3c0c9c468'
down_revision: Union[str, None] = '18e8f88c3f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leyendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['distritos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leyendas_description'), 'leyendas', ['description'], unique=False)
    op.create_index(op.f('ix_leyendas_id'), 'leyendas', ['id'], unique=False)
    op.create_index(op.f('ix_leyendas_title'), 'leyendas', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leyendas_title'), table_name='leyendas')
    op.drop_index(op.f('ix_leyendas_id'), table_name='leyendas')
    op.drop_index(op.f('ix_leyendas_description'), table_name='leyendas')
    op.drop_table('leyendas')
    # ### end Alembic commands ###
